# Custom Language File for Launcher Customizer

[ejs.app]
title = "Glory Nations Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/glorynations"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/glorynations"
supportLink = "https://discord.gg/glorynations"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Glory Nations"
welcomeDescription = "Préparez-vous à rejoindre l'aventure Glory Nations ! Un serveur Minecraft unique avec une communauté passionnée."
welcomeDescCTA = "Vous êtes à quelques clics de Glory Nations."

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "Connexion au serveur!"
joined = "Domine le monde"

[js.discord]
waiting = "Dans le launcher"
state = "{playerCount} joueurs en ligne"
